{
  "latest_version": [
    "4.2.0"
  ],
  "meta": {
    "description": "An error reporting utility for Zope3",
    "homepage": "http://pypi.python.org/pypi/zope.error",
    "license": "ZPL 2.1"
  },
  "versions": {
    "3.5.0": {
      "sha256": "af1bb6e35244be0337dfc01828a5ad8c81b9b4b6db9a1e56c437e2ee6b93e698",
      "url": "https://files.pythonhosted.org/packages/36/30/0096d1e3d6d3783c6ca9c46bfa80660676a40416a6285a54b036a8b3e22b/zope.error-3.5.0.zip"
    },
    "3.5.1": {
      "sha256": "d0158cdb14ecd30e3da45ddb234e07bec9503eab1975ac0668916fdc9e461110",
      "url": "https://files.pythonhosted.org/packages/67/2d/1613ce68842eb36dd6ad8bd2179bb237e7597b5dd9efcc931e786c18653d/zope.error-3.5.1.tar.gz"
    },
    "3.6.0": {
      "sha256": "de92b73216e10281da34c85c2d87cf4af323d41ef7d1d04b84e1019662000460",
      "url": "https://files.pythonhosted.org/packages/e9/25/3515ecdfee94596886d54e1efd7857934f5689f3873201196ae267cb9f68/zope.error-3.6.0.tar.gz"
    },
    "3.7.0": {
      "sha256": "d4f0ef8715d042576c886acd55d330ecc2afca55e32c4bc24a625b365de56617",
      "url": "https://files.pythonhosted.org/packages/80/08/8629e72be0d74be3199a0b1cf813cd25b2c54997862f5cb8955a72f9558b/zope.error-3.7.0.tar.gz"
    },
    "3.7.1": {
      "sha256": "0bdcaf4f548055da32f038271ac33856e88cff72112fff676424db5a4db948e2",
      "url": "https://files.pythonhosted.org/packages/66/0d/27add1de2d43ec2e4cf42f16a3fe57038bd4ea214da616043359aafd414e/zope.error-3.7.1.tar.gz"
    },
    "3.7.2": {
      "sha256": "1e95bf34c8ca99b3bdd88e1bc8bd8800c33c51e4a3239cb33786293a01300fc2",
      "url": "https://files.pythonhosted.org/packages/e2/d2/10dd1bfea41a2b1a8aebb54da0fc3ac8d5f84fb306b79151448334120836/zope.error-3.7.2.tar.gz"
    },
    "3.7.3": {
      "sha256": "d3ae426ba84ff74e68d33d9086073dfe056b039c289b4c8d5f6a4d71749fee3e",
      "url": "https://files.pythonhosted.org/packages/fb/21/a58a4a2f584c8f6af939811c40c6d7d307912621b687db0c62eeb0337e83/zope.error-3.7.3.tar.gz"
    },
    "3.7.4": {
      "sha256": "9e22106c88bdf1c7ebafb96eddf7bd2207db8994edde6b1de7e7dafa16cd080e",
      "url": "https://files.pythonhosted.org/packages/71/ff/3cee25c2badaf32bba893514538a063b4b712a5a3a22bb417f180ef50dd1/zope.error-3.7.4.tar.gz"
    },
    "4.0.0": {
      "sha256": "ae0856999f89ef4fa0e105c3f3ba867926c5c09820ef489ec1c152ee5656d0c7",
      "url": "https://files.pythonhosted.org/packages/a2/12/571186b07ede00fdd21654dd1d6410eedd2df8c8d87c4a956543b007a54d/zope.error-4.0.0.tar.gz"
    },
    "4.1.0": {
      "sha256": "6947ce62a0a36a8cba7fe8c49aa1105526e65cd784cc8782761b751b6af5b10a",
      "url": "https://files.pythonhosted.org/packages/78/9a/5f5b8cc786bbd41983bfb73199d8c8caf26d78c5775a850ca62ac8d0d1be/zope.error-4.1.0.zip"
    },
    "4.1.1": {
      "sha256": "4aff13e1aa58de343dfe2244a9241e891ca0f9657ae911ed781a9f167a3415f3",
      "url": "https://files.pythonhosted.org/packages/05/4d/14664ae7d7ed4dbde14cb9b694dcd1bc75db9fa58842f3615fe5d516b926/zope.error-4.1.1.tar.gz"
    },
    "4.2.0": {
      "sha256": "8f26153c225b7f4d6c1a2b2fb739048de6decb4be8e8376c1de1fed8c6198068",
      "url": "https://files.pythonhosted.org/packages/fc/61/dbcb391703bd0594e15186f5fd55e739d9550c3ce396e20fc58aa9a616c3/zope.error-4.2.0.tar.gz"
    }
  }
}