{
  "latest_version": [
    "4.1"
  ],
  "meta": {
    "description": "ZODB undo support for Zope2",
    "homepage": "http://pypi.python.org/pypi/ZopeUndo",
    "license": "ZPL 2.1"
  },
  "versions": [
    {
      "2.12.0": {
        "sha256": "5f2c077a23834773668a9badcffcaa227d2ee9b231d20ed8103b19be5cdf343d",
        "url": "https://files.pythonhosted.org/packages/59/b3/891937a2193b0a6a9c6a058ec3a426be75b7a83c9409b2bebe5d2a6d67ba/ZopeUndo-2.12.0.zip"
      },
      "4.0": {
        "sha256": "3ebc24b571af450b909492c688b72e81815feb7c780d4cff3236e4446c996718",
        "url": "https://files.pythonhosted.org/packages/31/97/c5c01955db8dcef3c74d46232c4f3aaad3f0e085bbdd0c89a7bae064fefe/ZopeUndo-4.0.zip"
      },
      "4.1": {
        "sha256": "b2bdb13a9682b5da9f7f204c7a8b70c5e3253d9e3acbd1b223726830948a5a7d",
        "url": "https://files.pythonhosted.org/packages/ce/40/51bc73896bdc23e1e16db55530c54f293d40d0a2c41e5a79efd4ea66dc1c/ZopeUndo-4.1.zip"
      }
    }
  ]
}