{
  "latest_version": [
    "2.7.2"
  ],
  "meta": {
    "description": "A simple use of exception errors",
    "homepage": "UNKNOWN"
  },
  "versions": {
    "2.7.2": {
      "sha256": "21723b4e62a09ee24ab5ce881b264a50ce98ea852c9f5ac481c22176069b6d6f",
      "url": "https://files.pythonhosted.org/packages/a2/c1/5e3ef6c3ce3d6eadf1a3bb3fb69c4d733ce7cddce40e773f6f5b8c9f005f/try_catch-2.7.2.zip"
    }
  }
}